[phases.setup]
nixPkgs = [
  "libx11",
  "libxext",
  "libxrender",
  "libgl1",
  "glibc",
  "gcc",
  "pkg-config",
  "python311Full",
  "cmake"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]